### ISSUE TITLE
Dropbox error

### ISSUE THREAD

**Issue by Backdrop9019** [zhuoxiao-chen/CEVT#1]
Hi,

Thank you for sharing the code.
Dropbox page is inaccessible. I'd appreciate it if you could restore it.

Thanks

**Comment by zhuoxiao-chen** [comment]
Unfortunately, the Dropbox link is not inaccessible. 

You can find the same datasets to download from [TA3N repo](https://github.com/cmhungsteve/TA3N).

We will also update the dataset link for this repo once we upload it again. 

Hope this can help you.
